server:
    port: 8080
    servlet:
        context-path: /services/rest
    tomcat:
        max-threads: ${MAX_THREADS:2000}



spring: 
    main:
        banner-mode: "off"     

logging: 
    level: 
        org: 
            springframework: INFO